name: test1
compose_files:
  - test1.compose.yml
---
name: test2
#reference: main
compose_files:
  - test2.compose.yml
#force_recreate: false
# main
---
name: test3
compose_files:
  - test1.compose.yml
