name: test-deploy
compose_files:
  - docker-compose.yml
force_recreate: true
external_secrets:
  TEST_PASSWORD: # Bitwarden Vault
    storeRef: bitwarden-login
    remoteRef: 
      key: 7293a970-2834-4490-a2c9-b41400c9295f
      property: password
