name: tagged-test
reference: v1.1.5
# dual
#working_dir: deploy/
# auto_discover: true
# auto_discover_opts:
#   depth: 1
---
reference: autodiscover
working_dir: apps/
auto_discover: true
auto_discover_opts:
  depth: 2
