name: test-deploy
reference: main
compose_files:
  - docker-compose.yml
env_files:
  - .env
environment:
  INLINE_ENV: hi
#force_recreate: false
#prune_images: true
force_image_pull: false
destroy:
  enable: true
  remove_volumes: true
  remove_images: false
  remove_dir: false
reconciliation:
  enabled: true
  restart_timeout: 10
  restart_limit: 5
  restart_window: 300
  events:
    #- stop
    #- die
    #- destroy
    #- unhealthy
    #- oom
    - kill
