name: test-deploy
reference: main
repository_url: https://github.com/kimdre/doco-cd.git
compose_files:
  - test.compose.yaml
env_files:
  - base.env
  - remote:test.env
---
name: test-deploy2
reference: main
repository_url: https://github.com/kimdre/doco-cd.git
compose_files:
  - test.compose.yaml
env_files:
  - base.env
  - prod.env
  - remote:test.env
