name: test-deploy
compose_files:
  - docker-compose.yml
force_recreate: true
external_secrets:
  TEST_PASSWORD: "op://Doco-CD/Secret Test/OTHER_SECRET" # 1Password
  DB_PASSWORD: "op://Doco-CD/Database/password" # 1Password
