name: app1
#reference: main
working_dir: deploy/app1
#compose_files:
#  - docker-compose.yml
#force_recreate: false
---
name: app2
working_dir: deploy/app2
#compose_files:
#  - docker-compose.yml
#force_recreate: false
