name: test-deploy
compose_files:
  - docker-compose.yml
force_recreate: true
external_secrets:
  TEST_PASSWORD: "arn:aws:secretsmanager:eu-west-1:571075516563:secret:test-db-YRkMAD/password"
  OTHER_PASSWORD: "arn:aws:secretsmanager:eu-west-1:571075516563:secret:test-db-YRkMAD"
