name: test-deploy
compose_files:
  - docker-compose.yml
force_recreate: true
external_secrets:
  TEST_PASSWORD: kv:secret:mysecret:password
  OTHER_PASSWORD: "kv:secret:mysecret:password"
  USERNAME: kv:secret:mysecret:username
  CERT: pki:pki:test.example.internal
