services:
  nginx:
    image: nginx
    profiles:
      - web
  
  traefik:
    image: traefik
    profiles:
      - web

  database:
    image: postgres
    profiles:
      - db
    environment:
      POSTGRES_PASSWORD: example
  
  memcached:
    image: memcached
