services:
  dummy:
    image: bash:latest
    scale: 0

  test:
    image: bash:latest
    #scale: 0
    restart: no
#    deploy:
#      #mode: global
#      restart_policy:
#        condition: none
    entrypoint: ["sh", "-ec"]
    environment:
      TZ: Europe/Berlin
      ID: 1
    command:
      - |
        echo "Hello world!"
        date
        sleep 15
    labels:
      cd.doco.job.enabled: "true"
      cd.doco.job.schedule: "@every 1m"
      #cd.doco.job.skip_running: "false"
      cd.doco.job.execution_mode: "one_off"
      cd.doco.job.run_on_deploy: "true"

  nginx:
    image: nginx:latest