services:
  frontend-init:
    image: nginx:alpine
    container_name: frontend-init
    restart: "no"
    user: "0"
    volumes:
      - frontend_static:/static
    entrypoint: ["/bin/sh", "-c"]
    command: ["rm -rf /static/* && date > /static/index.html"]
 
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    volumes:
      - frontend_static:/usr/share/nginx/html:ro
    ports:
      - "81:80"
    depends_on:
      frontend-init:
        condition: service_completed_successfully
 
volumes:
  frontend_static: