services:
  test:
    #container_name: test
    image: nginx
    restart: unless-stopped
    environment:
      SUPER_SECRET: "passw0rd_${TEST_PASSWORD}"
      TZ: Europe/Berlin
      HELLO: World!
      Foo: bar
    labels:
      test1test1: inject.${TEST_PASSWORD}
      test2: ignore.$${TEST_PASSWORD}
      other: $OTHER_PASSWORD
      username: $USERNAME
      ref_test: $REF_TEST
      a: d
    env_file: ./foo.env
    configs:
      - source: test.crt
        target: /test.crt
      - source: test.key
        target: /test.key

  scheduler-test:
    image: busybox:latest
    restart: no
    environment:
      TEST_PASSWORD: ${TEST_PASSWORD:-unset}
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        echo "env var interpolation test: '${TEST_PASSWORD}'"
        sleep 10
        echo Done
    labels:
      cd.doco.job.enabled: "true"
      cd.doco.job.schedule: "*/1 * * * *"
      cd.doco.job.execution_mode: "one_off"
      cd.doco.job.skip_running: "true"

configs:
  test.crt:
    #environment: CERT
    content: ${CERT:-empty}
  test.key:
    environment: CERT_KEY
