services:
  included:
    image: nginx:latest
    labels:
      included: 10
    configs:
      - include.conf
  other:
    image: nginx:latest
    labels:
      included: 1
      cd.doco.deployment.recreate.ignore: >-
        {
          configs: [app, nginx],
          secrets: [db],
          bindMounts: [/etc/caddy]
        }

configs:
  include.conf:
    file: include.conf
