services:
  test:
    scale: 1
    container_name: test
    image: nginx
    restart: unless-stopped
    environment:
      TZ: Europe/Berlin
      HELLO: World!
      Foo: bar
    env_file: ./foo.env
    ports:
      - "12345:80"
    volumes:
      - ./html/index.html:/usr/share/nginx/html/index.html
      - test:/test
      - ./asdf:/bind
    networks:
      test:

volumes:
  test:

networks:
  test:
