services:
  syncthing:
    extends:
      file: ../../../common/syncthing/compose.yaml
      service: syncthing
    volumes:
    #  - "/data/certs/:/data/certs"
    #  - "/data/backup/:/data/backup"
    - /tmp/syncthing:/var/syncthing"