services:
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    configs:
      - source: index.html
        target: /usr/share/nginx/html/index.html

configs:
  index.html:
    file: ./index.html
