services:
  test:
    scale: 1
    image: nginx
    restart: unless-stopped
    environment:
      TZ: Europe/Berlin
      SOME: Value
      id: 1
    volumes:
      - ./html:/usr/share/nginx/html0
      - test:/test
    env_file:
      - test.enc.env
    networks:
      test:

volumes:
  test:

networks:
  test:
