services:
  test:
    scale: 0
    image: nginx
    restart: unless-stopped
    environment:
      TZ: Europe/Berlin
      SOME: Value
      id: 3
    volumes:
      - ./html:/usr/share/nginx/html
      - test:/test
    env_file:
      - test.enc.env
    networks:
      test:

volumes:
  test:

networks:
  test:
